---
title: "Velib availability"
output: html_document
---

```{r}
install.packages("httr")
library(httr)
require(httr)
install.packages("jsonlite")
library(jsonlite)
require(jsonlite)


url <- "https://opendata.paris.fr/api/records/1.0/search/?dataset=velib-disponibilite-en-temps-reel&q=&facet=name&facet=is_installed&facet=is_renting&facet=is_returning&facet=nom_arrondissement_communes"
velib <- GET(url, verbose())
velib$status_code
http_status(velib)

headers(velib)

velib$content

velib_parse <- content(velib, "parse")
velib_text <- content(velib, "text")
velib_json <- fromJSON(velib_text, flatten = TRUE)
velib_df <- as.data.frame(velib_json$records)
View(velib_df)


```

```{r}
library(httr)
require(httr)
library(jsonlite)
require(jsonlite)


urlStatus <- "https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json"

urlInformations <- "https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_information.json"

status <- GET(urlStatus, verbose())
status_parse <- content(status, "parse")
status_text <- content(status, "text")
status_json <- fromJSON(status_text, flatten = TRUE)
status_df <- as.data.frame(status_json)

info <- GET(urlInformations, verbose())
info_parse <- content(info, "parse")
info_text <- content(info, "text")
info_json <- fromJSON(info_text, flatten = TRUE)
info_df <- as.data.frame(info_json)

View(status_df)
View(info_df)

```

```{r}
library(leaflet)
library(dplyr)

velib = left_join(info_df, status_df, by="data.stations.stationCode")

pal <- colorFactor (c("#FF0000FF", "#FFFF00FF", "#00FF00FF", "#00FFFFFF", "#0000FFFF", "#FF00FFFF"), domain = velib$data.stations.capacity)

popup_info = paste(velib$data.stations.name, "<br/>", "Capacité maximale de la station : ", velib$data.stations.capacity, "<br/>", "Vélos disponibles : ", velib$data.stations.num_bikes_available) 

leaflet()%>%addTiles()
leaflet()%>%addTiles()%>%addMarkers(data=velib, lat = ~data.stations.lat, lng = ~data.stations.lon, popup = ~popup_info, clusterOptions = markerClusterOptions(iconCreateFunction =
                                      JS("
                                          function(cluster) {
                                             return new L.DivIcon({
                                               html: '<div style=\"background-color:rgba(0,147,255,1)\"><span>' + cluster.getChildCount() + '</div><span>',
                                               className: 'marker-cluster'
                                             }); 
                                           }")))

```


